name: CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      version: ${{ steps.getInfo.outputs.version }}
      repoName: ${{ steps.getInfo.outputs.repoName }}
      artifactName: ${{ steps.getInfo.outputs.artifactName }}
      actionUrl: ${{ steps.getInfo.outputs.actionUrl }}
    steps:
    - name: 获取信息
      id: getInfo
      uses: actions/github-script@v8
      with:
        script: |
          const onEventName = "${{ github.event_name }}";
          const refName = "${{ github.ref }}";
          let repoName = "${{ github.repository }}";
          repoName = repoName.replace("${{ github.repository_owner }}/", "");
          let artifactName = `${repoName}-CI-Dispatch-Build-${{ github.run_number }}`;

          if (onEventName == "pull_request") {
            artifactName = `${repoName}-CI-PR_${{ github.event.pull_request.number }}-Build-${{ github.run_number }}`;
          }

          if(onEventName == "push" && refName.startsWith("refs/tags/")){
            artifactName = `${repoName}-Release-${{ steps.getVersion.outputs.version }}`;
            const version = refName.replace("refs/tags/", "");
            core.setOutput('version', `${version}`);
            core.info(`Release version: ${version}`);
          }

          core.setOutput('repoName', `${repoName}`);
          core.setOutput('artifactName', `${artifactName}`);
          core.setOutput('actionUrl', '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}');
    - name: 拉取代码
      uses: actions/checkout@v6
    - name: 安装java8
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: 缓存本地 maven 仓库
      uses: actions/cache@v5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: 设置 pom.xml 的版本号
      if: github.event_name == 'push' && startsWith('${{ github.ref }}', 'refs/tags/')
      run: |
        echo "::warning::对 pom.xml 中 project 版本号进行设置，设置的版本号为 ${{ steps.getVersion.outputs.version }}"
        mvn versions:set -DnewVersion=${{ steps.getInfo.outputs.version }}
    - name: 获取 pom.xml 的信息
      id: getPomInfo
      run: |
        echo "groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    - name: 输出获取到的 pom.xml 的信息
      run: |
        echo Group id: ${{ steps.getPomInfo.outputs.groupId }}
        echo Artifact id: ${{ steps.getPomInfo.outputs.artifactd }}
        echo Version: ${{ steps.getPomInfo.outputs.version }}
    - name: 构建
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
    - name: 收集构建文件
      uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.getInfo.outputs.artifactName }}
        path: staging

  release:
    runs-on: ubuntu-slim
    if: github.event_name == 'push' && startsWith('${{ github.ref }}', 'refs/tags/')
    needs: build
    timeout-minutes: 5
    steps:
    - name: 拉取代码
      uses: actions/checkout@v6
    - name: 下载发布需要的文件
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifactName }}
        path: staging
    - name: 列出需要发布的文件
      run: ls -lah ./staging
    - name: 发布新版本
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ needs.build.outputs.version }}
        name: ${{ needs.build.outputs.version }}
        token: ${{ github.token }}
        bodyFile: ./docs/changelogs/${{ needs.build.outputs.version }}.md
        artifacts: ./staging/*.*